### ISSUE TITLE
Parse bad responses from server showing maintenance mode

### ISSUE THREAD

**Issue by sralloza** [sralloza/vcm#115]
<details>
<summary>Traceback from python</summary>

```python
>>> import requests
>>> requests.get("https://campusvirtual.uva.es")
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Python\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Python\lib\http\client.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <html>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Python\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Python\lib\http\client.py", line 278, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('<html>\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('<html>\n'))
```
</details>

Using an [online tool](https://apitester.com/) to view the raw response:
Request:
```
GET / HTTP/1.1
Host: campusvirtual.uva.es
Accept: */*
User-Agent: Mozilla/5.0 (compatible; Rigor/1.0.0; http://rigor.com)
```

Response:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<center><h1><span style="color:#E80C97">
Estimado usuari@,

Los servicios del campus virtual UVa permanecen cerrados desde el lunes 17 de agosto para volcar el curso 2019-2020 al servicio de cursos anteriores, llevar a cabo actuaciones en la infraestructura y en el control de versiones de moodle y extensiones instaladas y para la carga inicial del nuevo curso 2020-2021.
                                               
Abriremos el servicio a todos los usuarios en la semana del 24 al 28 de agosto en cuanto finalicemos todas las actuaciones técnicas programadas.   

Disculpa las molestias ocasionadas.
                                                                                                      
Servicio técnico del Campus Virtual Uva (S.T.I.C.)
</h1></center> 
</body>
</html>
```

As you can see, the server sends no HTTP headers, so python tries to parse the first line (`<head>`) as if it were a header.

**Comment by sralloza** [comment]
Project archived
