### ISSUE TITLE
TypeError raised when setting logging level in lowercase

### ISSUE THREAD

**Issue by sralloza** [sralloza/vcm#20]
```
>>>vcm settings set general.logging-level debug
Traceback (most recent call last):
  File "D:/.scripts/vcm/cli.py", line 4, in <module>
    main()
  File "D:\.scripts\vcm\vcm\main.py", line 115, in main
    setattr(settings_class, key, opt.value)
  File "D:\.scripts\vcm\vcm\core\settings.py", line 129, in __setattr__
    self[key] = value
  File "D:\.scripts\vcm\vcm\core\settings.py", line 136, in __setitem__
    raise TypeError("%r must be one of %r" % (key, expected_type))
TypeError: 'logging-level' must be one of ('NOTSET', 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
```

**Comment by sralloza** [comment]
Must catch that exception and pass the message to `exit()`

**Comment by sralloza** [comment]
It is already catched by `safe_exit()` decorator in `main()`
